name: Test

on:
  push:
    # all branches
    branches:
      - '**'
    # no tags
    tags-ignore:
      - '**'

jobs:
  testlib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x, 25.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Log versions
      - run: npm --version; node --version
      - run: npm ci
      # make sure tests pass
      - run: npm test
      # make sure we can build successfully
      - run: npm run build
